### ISSUE TITLE
New path down real time 

### ISSUE THREAD

**Issue by marvinh** [Stenzel/newpathdown#2]
hi I am trying to use new path down in real time but at 0.25 ratio of the sample the lower i got i get lots of crackling sounds any idea what it could be?

sounds perfect when running in demo.cpp but when using it in real time i am getting some crackling at low ratios

`//==============================================================================
void MySamplerVoice::renderNextBlock (AudioBuffer<float>& outputBuffer, int startSample, int numSamples)
{
    if (auto* playingSound = static_cast<MySamplerSound*> (getCurrentlyPlayingSound().get()))
    {
        auto& data = *playingSound->data;
        
        const float* const inR = data.getNumChannels() > 1 ? data.getReadPointer (1) : nullptr;

        float* outL = outputBuffer.getWritePointer (0, startSample);
        float* outR = outputBuffer.getNumChannels() > 1 ? outputBuffer.getWritePointer (1, startSample) : nullptr;

        
        while (numSamples >= 0)
        {
            //auto pos = (int) sourceSamplePosition;
            //auto alpha = (float) (sourceSamplePosition - pos);
            //auto invAlpha = 1.0f - alpha;

            // just using a very simple linear interpolation here..
            //float l = (inL[pos] * invAlpha + inL[pos + 1] * alpha);
            //float r = (inR != nullptr) ? (inR[pos] * invAlpha + inR[pos + 1] * alpha)
            //                           : l;

            
            
            
            SrcL = rL.process16(SrcL, myOutL);
        
            for(int i = 0; i < 16; i++) {
                
                float l = myOutL[i];
                myOutL[i] = 0;
                float r = l;
                auto envelopeValue = ampDecay.process();
                
                l *= lgain * envelopeValue;
                r *= rgain * envelopeValue;
                
                if (outR != nullptr)
                {
                    *outL++ += l;
                    *outR++ += r;
                }
                else
                {
                    *outL++ += (l + r) * 0.5f;
                }
                
            }
            
            numSamples-=16;
            
            
            if (ampDecay.mStage == DEnvelope::DStage::OFF)
            {
                stopNote (0.0f, false);
                break;
            }
            
            if(SrcL == nullptr) {
                stopNote (0.0f, false);
                SrcL = data.getWritePointer(0, 0);
                break;
            }
            
        }
        
    }
}`

**Comment by Stenzel** [comment]
Hello Marvinh,

Looks like you expect numSamples to be divisible by 16, in many DAWs this is not the case.
You need an adapter for arbitrary block sizes.

Stefan

**Comment by marvinh** [comment]
thank you i thought that was the case but just more apparent at very low ratios high ratios you cant hear any crackling

**Comment by marvinh** [comment]
Hi stefan I modified for real time by processing 1 sample at a time instead of 16 by setting the values from 16 to 1 works perfectly i will share my project with you once i am done thank you for this and your talk at adc
